### ISSUE TITLE
BluetoothAdapter: bluetooth le advertising not supported

### ISSUE THREAD

**Issue by radames** [ludwigmace/simpble#1]
I'm trying on my Nexus 4, do you know if my chipset supports Advertising? What hardware are you using?

**Comment by ludwigmace** [comment]
Unfortunately the Nexus 4 doesn't support advertising.  In fact my Nexus 5 only kinda halfway supported it if you did a custom compile.  I tested on a recent Moto E 4G.  Android devices that come from the factory with Lollipop should support Advertising.

**Comment by radames** [comment]
perfect, thanks! I'm looking forward to test it some time,
